### ISSUE TITLE
Using specific directory for citar notes

### ISSUE THREAD

**Issue by gnava** [pprevos/denote-citar#1]
Hi,

thanks for this code, I've been using and though it wanted to place citar notes in a specific directory (usually a subdirectory of denote-directory). I think this migh be useful, so you can define, say, a `denote-citar-directory` to be nil or a directory and pass it to the `denote` command:
```
(denote
     ;; Replace underscores in citation key
     (replace-regexp-in-string "_" "-" key)
     (denote-citar--keywords-prompt)
     nil
     denote-directory)
```

I'm providing a patch though it might not be the proper way to implement this (limited elisp knowledge here).

https://gist.github.com/gnava/b33eadb51e71abd9114904c04e7bbb72

best,

guille

**Comment by pprevos** [comment]
Hi Guille,

Thanks for the suggestion. I am also still learning Elisp.

I am current focusing on another Emacs project before I complete the more complex Citar integration.

Storing them in another folder is a good suggestion. In my code I have forced the `bib` filetag to ensure that Citar knows which files are related to the bibliography. Placing them in a subfolder is another method.


Regards

P:)

**Comment by gnava** [comment]
thanks! (I've seen this has already been addressed)

**Comment by pprevos** [comment]
Thanks for closing the issue. @jloow has massively improved the code.
