### ISSUE TITLE
Obsolete symbols, some further integration

### ISSUE THREAD

**Issue by jloow** [pprevos/denote-citar#2]
I ran into some problems after starting to use this package yesterday: when creating new notes, the reference wasn't inserted. I was able to determine that this due to two obsolete symbols in the function `denote-citar-file--create-note` (see https://protesilaos.com/emacs/denote-changelog).

I rewrote the function slightly to get it working again:

```elisp
(defun denote-citar-file--create-note (key &optional entry)
  "Create a bibliography note through Citar."
  (let ((denote-file-type nil)) ; make sure it is Org
    (denote
     ;; Replace underscores in citation key
     (replace-regexp-in-string "_" "-" key)
     (denote-citar--keywords-prompt))
    ;; This sort of works now. It's not pretty, but hey.
    ;; denote-last-buffer was obsolete.
    ;; denote-retrieve--id-front-matter-key-regexp was obsolete.
    (with-current-buffer (current-buffer)
      (save-excursion
	(goto-char (point-min))
	(re-search-forward "^[^#]")
	(search-backward "#")
	(goto-char (point-at-eol))
        (newline)
        (insert (format "#+reference:  %s" key))))))
```

I'm quite bad with regex, so there's probably a nicer way of doing this. From what I can tell, though, this works.

Since I was already at it, I decided to see if I could get the integration with e.g. `citar-open` to work. I think I managed to get a basic implementation working; perhaps it's useful for future work.

Much of this work is writing our own `citar-files--get-notes` function (my function is largely based on `citar-file--directory-files`, which `citar-files--get-notes` relies on). The new function looks like this:

```elisp
(defun denote-citar--get-notes (&optional keys)
   (let ((files (make-hash-table :test 'equal))
	;; For now, we only support one extension.
	(org-files-regexp ".*\.org$")
	(marker1 nil)
	(marker2 nil)
	(dirs citar-notes-paths))
    (prog1 files
      (dolist (dir dirs)
	(when (file-directory-p dir)
	  (dolist (file (directory-files dir t ".*\.org$"))
	    ;; There certainly is a more elegant way of doing this
	    (with-current-buffer (get-buffer (find-file-noselect file))
	      (save-excursion
		;; Not sure if this is needed
		(goto-char (point-min))
		;; This should put us at the beginnig of the reference
		;; name. If this search fails, we are not dealing with
		;; a notes file for a reference.
		(when (search-forward "#+reference: " nil t)
		  ;; Here we select the reference name
		  (forward-to-word 1)
		  (setq marker1 (point))
		  (end-of-line)
		  (setq marker2 (point))
		  (if keys
		      (dolist (key keys)
			(when (string= key
				       (buffer-substring-no-properties marker1 marker2))
			  (push file (gethash key files))))
		    (let ((key (buffer-substring-no-properties marker1 marker2)))
		      (push file (gethash key files))))))))))
      ;; Reverse file lists because push adds elements to the front
      (maphash (lambda (key filelist)
                 (puthash key (nreverse filelist) files))
	       files))))
```

(Note that this implementation takes into consideration `citar-notes-path`.)

We also need a new `citar-file--has-notes`. Our version will look more or less the same only, for some reason, I couldn't use `let` and instead had to use `setq`:

```elisp
(defun denote-citar--has-notes ()
  (setq notes (denote-citar--get-notes))
    (unless (hash-table-empty-p notes)
      (lambda (citekey) (and (gethash citekey notes) t))))
```

Then we simply register a new note source with our new functions:

```elisp
(citar-register-notes-source
 'denote-citar-source (list :name "Denote Notes"
			    :category 'file
			    :items 'denote-citar--get-notes
			    :hasitems 'denote-citar--has-notes
			    :open 'find-file
                            :create 'denote-citar-file--create-note))
(setq citar-notes-source 'denote-citar-source)
```

I haven't tested this extensively, but it seems to work so far.

**Comment by pprevos** [comment]
Hi, Thanks so much for the contribution - you have pretty much written the package. Will you submit it as a push into this repo?

I have not had much time to look into learning more Elisp to make this work properly and Denote is evolving very fast. Thanks for taking me many steps further - looking forward to reverse-engineering what you did.

**Comment by jloow** [comment]
Glad I could help! Thank you for starting this package. It really helped me
to get started.

I'll try to submit a pull request during the week. It's been a while (I'm
not a programmer by trade) but I think I remember how it's done.

**Comment by pprevos** [comment]
No worries, I am neither a programmer. I only do some data science coding and trying to learn elisp.

**Comment by pprevos** [comment]
I will continue to do some work on this package over the Christmas holidays and hope to be able to produce a stable integration between Denote and Citar.

I currently use Citar and Denote but just manually add citation links. A backlink to the BibTex file would be nice.

P.S. we seem to have similar interests. One of my favorite side jobs is to teach engineers to code instead of using spreadsheets.

**Comment by jloow** [comment]
Now I've created to PR (#3). I think I did everything correctly. The submitted code is slightly different from the code in this issue, just some minor additions and more extensive comments.

> P.S. we seem to have similar interests. One of my favorite side jobs is to teach engineers to code instead of using spreadsheets.

Yeah, it noticed! :) Always fun to meet people with similar interests. And I too have an engineering background but now do mostly social science.
